In [1]:
import numpy as np
import pandas as pd

In [3]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [7]:
df = pd.read_csv('heart.csv')

In [9]:
df.head

<bound method NDFrame.head of       age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2  

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [21]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()


In [23]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [25]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [31]:
from sklearn.metrics import accuracy_score, confusion_matrix
print("Accuracy score of LogisticRegression:", accuracy_score(y_test,y_pred1))
print("Accuracy score of Decision Tree:", accuracy_score(y_test,y_pred2))

Accuracy score of LogisticRegression: 0.8439024390243902
Accuracy score of Decision Tree: 0.9804878048780488


In [35]:
confusion_matrix(y_test,y_pred1)

array([[83, 22],
       [10, 90]], dtype=int64)

In [39]:
print("Logistic Regression Confusion MAtrix:")
print("-"*50)
pd.DataFrame(confusion_matrix(y_test,y_pred1), columns=list(range(0,2))) 

Logistic Regression Confusion MAtrix:
--------------------------------------------------


0   1
0  83  22
1  10  90

In [43]:
print("Decision Tree Confusion Matrix:")
print("-"*50)
pd.DataFrame(confusion_matrix(y_test,y_pred2), columns=list(range(0,2)))

Decision Tree Confusion Matrix:
--------------------------------------------------


0    1
0  101    4
1    0  100

In [49]:
result = pd.DataFrame()
result['Actual label'] = y_test
result['LogisticRegression Prediction'] = y_pred1
result['DecisionTree predicton'] = y_pred2

In [51]:
result.sample(10)

Actual label  LogisticRegression Prediction  DecisionTree predicton
291             0                              0                       0
70              0                              0                       0
160             0                              0                       0
662             1                              1                       1
694             0                              0                       0
576             1                              1                       1
465             1                              1                       1
223             1                              1                       1
310             0                              0                       0
536             1                              1                       1

In [53]:
from sklearn.metrics import precision_score, recall_score, f1_score


In [55]:
print("LogisticRegression Confusion MAtrix")
print('-'*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1), columns=list(range(0,2)))
print(cdf)
print('-'*50)
print("Precision:", precision_score(y_test, y_pred1))
print("Recall:", recall_score(y_test,y_pred1))
print("F1-Score:", f1_score(y_test, y_pred1))

LogisticRegression Confusion MAtrix
--------------------------------------------------
    0   1
0  83  22
1  10  90
--------------------------------------------------
Precision: 0.8035714285714286
Recall: 0.9
F1-Score: 0.8490566037735849


In [59]:
print("DecisionTree Confusion Matrix")
print('-'*50)
cdf1 = pd.DataFrame(confusion_matrix(y_test,y_pred2), columns=list(range(0,2)))
print(cdf1)
print('-'*50)
print("Precision:", precision_score(y_test,y_pred2))
print("Recall:", recall_score(y_test,y_pred2))
print("F1-Score:", f1_score(y_test,y_pred2))

DecisionTree Confusion Matrix
--------------------------------------------------
     0    1
0  101    4
1    0  100
--------------------------------------------------
Precision: 0.9615384615384616
Recall: 1.0
F1-Score: 0.9803921568627451


In [63]:
precision_score(y_test,y_pred1, average=None)


array([0.89247312, 0.80357143])

In [71]:
precision_score(y_test,y_pred2, average='weighted')

0.9812382739212008

In [73]:
recall_score(y_test,y_pred1, average=None)

array([0.79047619, 0.9       ])

In [75]:
recall_score(y_test,y_pred2, average=None)

array([0.96190476, 1.        ])

In [77]:
f1_score(y_test, y_pred1, average=None)

array([0.83838384, 0.8490566 ])