In [15]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

In [17]:
df = pd.read_csv('titanic.csv', usecols=['Age', 'Fare', 'Survived'])

In [19]:
df.head()

Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [21]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [23]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [25]:
X_train.head()

Age     Fare
331  45.5  28.5000
733  23.0  13.0000
382  32.0   7.9250
704  26.0   7.8542
813   6.0  31.2750

In [29]:
si = SimpleImputer()
X_train_trf = si.fit_transform(X_train)
X_test_trf = si.transform(X_test)

In [31]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf,y_train)

y_pred = clf.predict(X_test_trf)

from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred)


0.6480446927374302

In [35]:
from sklearn.impute import MissingIndicator
mi = MissingIndicator()

mi.fit(X_train)

MissingIndicator()

In [37]:
mi.features_

array([0], dtype=int64)

In [39]:
X_train_missing = mi.transform(X_train)

In [41]:
X_train_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [43]:
X_test_missing = mi.transform(X_test)

In [45]:
X_test_missing

array([[ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [49]:
X_train['Age_NA'] = X_train_missing

In [51]:
X_test['Age_NA'] = X_test_missing

In [65]:
X_test

array([[ 29.49884615,  15.2458    ,   1.        ,   1.        ],
       [ 31.        ,  10.5       ,   0.        ,   0.        ],
       [ 20.        ,   7.925     ,   0.        ,   0.        ],
       [  6.        ,  33.        ,   0.        ,   0.        ],
       [ 14.        ,  11.2417    ,   0.        ,   0.        ],
       [ 26.        ,  78.85      ,   0.        ,   0.        ],
       [ 29.49884615,   7.75      ,   1.        ,   1.        ],
       [ 16.        ,  18.        ,   0.        ,   0.        ],
       [ 16.        ,   7.75      ,   0.        ,   0.        ],
       [ 19.        ,  26.2833    ,   0.        ,   0.        ],
       [ 37.        ,  53.1       ,   0.        ,   0.        ],
       [ 44.        ,   8.05      ,   0.        ,   0.        ],
       [ 29.49884615,  25.4667    ,   1.        ,   1.        ],
       [ 30.        ,   7.225     ,   0.        ,   0.        ],
       [ 36.        ,  13.        ,   0.        ,   0.        ],
       [ 16.        ,  39

In [55]:
si = SimpleImputer(add_indicator=True)

In [59]:
X_train = si.fit(X_train)

In [61]:
X_test = si.transform(X_test)

In [71]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf,y_train)

y_pred = clf.predict(X_test_trf)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6480446927374302